services:
  app:
    build:
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "8000:8000"
    user: "${UID:-1000}:${GID:-1000}"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/laravel-app
  db:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
