services:
  app:
    build:
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "8000:8000"
    user: "${UID:-1000}:${GID:-1000}"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/laravel-app

